### ISSUE TITLE
Convert commands to SlashCommands

### ISSUE THREAD

**Issue by drobati** [drobati/alia-bot#68]
It would be cool to use SlashCommands functionality so that users can easily interact with commands through the UI.

**Comment by drobati** [comment]
unrelated: testing github webhooks

**Comment by gvarner13** [comment]
Which commands should be moved to slash commands? I was going to start with the QR code one as it just needs a string passed to it. Also, where should I put the deploy-commands script?

**Comment by drobati** [comment]
The QR code one sounds good to me! :)

Throw it in https://github.com/drobati/alia-bot/tree/master/scripts
